# Generated by Django 3.1.2 on 2020-10-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201006_1210'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.beer'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lineitem', to='checkout.order'),
        ),
    ]
