# Generated by Django 3.1.2 on 2020-10-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201014_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
