# Generated by Django 3.1.2 on 2020-10-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201006_1210'),
        ('checkout', '0004_order_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.beer'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='checkout.order'),
        ),
    ]
