# Generated by Django 3.1.2 on 2020-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name_plural': 'Breweries'},
        ),
        migrations.AddField(
            model_name='beer',
            name='image_url',
            field=models.URLField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='beer',
            name='sku',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='style',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
