# Generated by Django 3.1.2 on 2020-11-01 16:43

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='record',
            name='track_listing',
            field=django_mysql.models.ListCharField(models.CharField(max_length=25), max_length=2500, size=50),
        ),
    ]
