# Generated by Django 3.1.2 on 2020-11-01 16:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201101_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='track_listing',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=3600, size=50),
        ),
    ]
