# Generated by Django 3.1.2 on 2020-11-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_record_album_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
